name: flutter_recipe_generator
description: "A Recipe Generator from several images."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.0.0
  camera: ^0.11.0+2
  file_picker: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4
  device_info_plus: ^10.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  fluttertoast: ^8.2.5
  http: ^0.13.6 
  flutter_markdown: ^0.6.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.jpg"
  adaptive_icon_foreground: "assets/images/splash.jpg"
  adaptive_icon_background: "#121212"

flutter_native_splash:
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  color: "#000000"
  image: "assets/images/splash.jpg"